import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "../public/fontawesome/css/all.css"
import { ClerkProvider } from '@clerk/nextjs'
import RecoidContextProvider from './recoilContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider afterSignInUrl='/signup-nex'>
    <html lang="en">
      
      <body className={inter.className}>
        <RecoidContextProvider>
        {children}
        </RecoidContextProvider>
      </body>
    </html>
    </ClerkProvider>
  )
}
